version: '3'

services:

  app:
    build:
      context: ./node
    container_name: app
    hostname: nodejsserver
    restart: always
    ports:
      - "3000:3000"
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    tty: true
    restart: always
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app
      - db

networks:
  node-network:
    driver: bridge
